import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, Bool
from nav_msgs.msg import Odometry
from scipy.spatial.transform import Rotation as R
import math
import numpy as np
import time

class LowLevelCtrl(Node):
    def __init__(self):
        super().__init__('low_level_ctrl')

        # Subscribers
        self.subscription_ref_spd = self.create_subscription(
            Float32, '/ref_spd', self.ref_spd_callback, 2)
        self.subscription_curr_odom = self.create_subscription(Odometry, '/odometry/filtered', self.odom_callback, 10)
        # Publishers
        self.publisher_throttle = self.create_publisher(Float32, '/rover/throttle', 50)
        self.publisher_steering = self.create_publisher(Float32, '/rover/steering', 50)

        # add a timer to continuously publish throttle control data
        # 10 Hz is the ref speed generated by tactical node
        self.timer = self.create_timer(1.0 / 10.0, self.timer_callback)

        # Declare parameters, default value
        self.declare_parameter('is_steering_correction', 0)           # decide whether to use steering correction
        self.declare_parameter('is_throttle_correction', 0)           # decide whether to use throttle correction
        self.is_steering_correction = self.get_parameter('is_steering_correction').value # Read parameters
        self.is_throttle_correction = self.get_parameter('is_throttle_correction').value # Read parameters

        # State 
        self.aeb_triggered = Bool(data=False)
        self.ref_spd = 0.0
        self.ref_heading = 0.0

        # Control Variables
        self.throttle = 0.0
        self.kp = 0.5 # Proportional gain
        self.ki = 0.001 # Integral gain
        self.output_limits = [0.0, 100.0] # (min, max) output
        self.integral = 0.0
        self.last_time = None
        self.vel = 0.0
        self.heading_angle = 0.0
        self.threshold_heading = math.pi/18 # 10 degre
        self.ctrl_steer_angle = 5.0 # 5 degree
        self.flag = 0 # judge if newly executed

    def ref_spd_callback(self, msg):
        """Check the reference speed data, update the throttle control value."""
        self.ref_spd = msg.data
        self.throttle = self.spd_to_throttle(self.ref_spd)
        #self.get_logger().info(f"The reference throttle is {self.throttle}.") #, throttle_duration_sec=1.0)

    def odom_callback(self, msg):
        """Check the current longitudial velocity and vehicle heading"""
        self.vel = msg.twist.twist.linear.x
        # Extract orientation quaternion
        orientation_q = msg.pose.pose.orientation
        r = R.from_quat([orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w])
        # Convert to Euler angles: here 'xyz' = roll, pitch, yaw
        # `degrees=True` returns angles in degrees; omit for radians
        _, _, self.heading_angle = r.as_euler('xyz')

    def timer_callback(self):
        """Publish motor commands at a fixed rate of 10Hz"""
        throttle_val = self.throttle
        self.publisher_throttle.publish(Float32(data=throttle_val))
        self.get_logger().info(f"The reference throttle is {throttle_val}.") #, throttle_duration_sec=1.0)
        if self.is_steering_correction:
            steer_val = self.cal_steering()
        else:
            steer_val = 0.0
        self.publisher_steering.publish(Float32(data=steer_val))


    def spd_to_throttle(self, ref_spd):
        self.get_logger().info(f"Receive ref spd= {ref_spd}")
        """Convert the reference speed to the throttle control value, use a open test mapping, this is NOT a closed-loop control."""
        if ref_spd == 0.0:
            self.get_logger().info("The reference speed is 0.", throttle_duration_sec=1.0)
            return 0.0
        if ref_spd < 1 or ref_spd > 3:
            self.get_logger().warn("The reference speed must be from the range of [1, 3].", throttle_duration_sec=1.0)
            return 0.0
        else:
            return (ref_spd + 0.62)/0.04

    def cal_steering(self):
        """Steer back the vehicle heading if it deviates too much"""
        err = self.heading_angle - self.ref_heading
        # Apply correction only if deviation exceeds threshold
        if abs(err) < self.threshold_heading:
            return 0.0 # No correction needed
        else:
            self.get_logger().info("heading_angle {0}".format(err), throttle_duration_sec=1.0)
            # Clip to max steering range
            if err > 0:
                return self.ctrl_steer_angle
            else:
                return -self.ctrl_steer_angle


def main(args=None):
    rclpy.init(args=args)
    node = LowLevelCtrl()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()